crud/account/urls.py
from django.urls import path
from account import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include
import blog.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.main, name='main'),
    path('detail/<str:id>/', blog.views.detail, name='detail'),
    path('write/', blog.views.write, name='write'),
    path('write/create', blog.views.create, name='create'),
    path('base/', blog.views.base, name='base'),
    path('edit/<str:id>/', blog.views.edit, name='edit'),
    path('delete/<str:id>/', blog.views.delete, name='delete'),
    path('blog/hashtag/', blog.views.hashtagform, name='hashtag'),
    path('blog/<int:hashtag_id>/search/', blog.views.search, name='search'),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    age = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)

crud/blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.

#Blog 생성
class Blog(models.Model):
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=100, default='이름을 입력해주세요')
    pub_date = models.DateTimeField('date published')
    content = models.TextField()
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    image = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.title

#댓글 모델
class Comment(models.Model):
    def __str__(self):
        return self.text

    post_id = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=50)

#해쉬태그
class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

crud/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('age', 'address',)

crud/blog/forms.py
from django import forms
from .models import Blog,Comment, Hashtag

class CreateForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'writer', 'content', 'hashtags', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

crud/account/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('base')
        else:
            return render(request, 'account/signup.html', {'form': form})
    else:
        form = CustomUserCreationForm()
        return render(request, 'account/signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('base')
        else:
            return render(request, 'account/login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'account/login.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('base')

crud/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Blog, Hashtag
from .forms import CreateForm, CommentForm, HashtagForm

# Create your views here.

def main(request):
    blogs = Blog.objects
    hashtags = Hashtag.objects
    return render(request, 'blog/main.html', {'blogs':blogs, 'hashtags':hashtags})

def detail(request, id):
    blog = get_object_or_404(Blog, id=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post_id = blog
            comment.text = form.cleaned_data['text']
            comment.save()
            form.save_m2m()
            return redirect('detail', id)
    else:
        form=CommentForm()
        return render(request, "blog/detail.html", {'blog':blog, 'form':form})

def write(request):
    return render(request, 'blog/write.html')

def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.pub_date = timezone.now()
            form.save()
            return redirect('main')
    else:
        form = CreateForm
        return render(request, 'blog/write.html', {'form':form})

def base(request):
    return render(request, 'blog/base.html')

def edit(request, id):
    blog = get_object_or_404(Blog, id = id)
    if request.method == "POST":
        form = CreateForm(request.POST, instance=blog)
        if form.is_valid():
            form.save(commit=False)
            form.save()
            return redirect('main')
    else:
        form = CreateForm(instance=blog)
    return render(request, 'blog/edit.html', {'form':form})

def delete(request, id):
    delete_blog = get_object_or_404(Blog, id = id)
    delete_blog.delete()
    return redirect ('main')

def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request, 'blog/hashtag.html', {'form':form, "error_message": error_message})
            else:
                hashtag.name = form.cleaned_data['name']
                hashtag.save()
            return redirect('main')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'blog/hashtag.html', {'form':form})

def search(request, hashtag_id):
    hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
    return render(request, 'blog/search.html', {'hashtag':hashtag})

crud/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CRUD 과제</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">CRUD main</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'main' %}">main</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'create' %}">write</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'hashtag' %}">Add hashtag</a></li>
                        {% if user.is_active %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">로그아웃</a></li>
                            <li class="nav-item"><a class="nav-link">{{ user.username }}님 안녕하세요.</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">로그인</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">회원가입</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">멋쟁이 사자처럼
                        </h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">밑에 글을 작성하세요</p>
                        {% block bord %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 멋쟁이 사자처럼</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

crud/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block bord %}
<section class="page-section" id="services">
    <div class="container px-4 px-lg-5">
        <h2>제목 : {{blog.title}}</h2>
        <hr class="divider" />
        <p>작성 일자 및 시간 : {{ blog.pub_date }}</p>
        <p>글쓴이 : {{ blog.writer }}</p>
        <p>내용 : {{ blog.content }}</p>
        {% if blog.image %}
            <img src="{{ blog.image.url }}" width="250" height="250" alt="Card image cap">
        {% endif %}
        <hr>
        {% for hashtag in blog.hashtags.all %}
            <span>{{ hashtag.name }}</span>
        {% endfor %}
        <br>
        <a href="{% url 'edit' blog.id %}">수정하기</a>
        <a href="{% url 'delete' blog.id %}">삭제하기</a>
        <br>
        <br>
        <br>
        {% for comment in blog.comments.all %}
            <p>{{ comment.text }}</p>
        {% endfor %}
        <form method="POST" action="{% url 'detail' blog.id %}">
            {% csrf_token %}
            <p>{{ form.as_p }}</p>
            <input type="submit" value="submit">
        </form>
    </div>
</section>
{% endblock %}

crud/blog/templates/blog/edit.html
{% extends 'blog/base.html' %}
{% load static %}

{% block bord %}

<body style="text-align: center">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table> 
        <button type="submit">작성</button>
    </form>
</body>

{% endblock %}

crud/blog/templates/blog/hashtag.html
{% extends 'blog/base.html' %}

{% block bord %}
<br><br>
<div class="container px-4 px-lg-5">
<h1>New Hashtag</h1>
  <span class="subheading">해시태그를 추가하는 페이지입니다.</span>
        {{ error_message }}
        <form method="POST">
            {% csrf_token %}
            <br><br>
            <table>
                {{form.as_table}}
            </table>
            <br>
            <input class="btn btn-dark" type="submit" value="제출하기">
        </form>
</div>
<br><br>
{% endblock %}

crud/blog/templates/blog/main.html
{% extends 'blog/base.html' %}
{% load static %}

{% block bord %}
<div class="row gx-4 gx-lg-5 justify-content-center">
<section id="services">
    <div class="container px-4 px-lg-5">
        <h2 class="text-center mt-0"></h2>
        <hr class="divider" />
        {% for blogs in blogs.all %}
        <h1>제목 :<a href="{% url 'detail' blogs.id %}">{{ blogs.title }}</a></h1>
        <p>작성자 : {{ blogs.writer }}</p>
        <p>작성 일자 및 시간 : {{ blogs.pub_date }}</p>
        {% if blogs.image %}
          <img src="{{ blogs.image.url }}" width="250" height="250" alt="Card image cap">
        {% endif %}
        <hr>
        {% endfor %}
        <br>
        <div class="dropdown">
         <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Hashtag
         </button>
         <div class="dropdown-menu" aria-labelledby="dropdownMenuButton"></div>
           {% for hashtag in hashtags.all %}
           <a class="dropdown-item" href="{% url 'search' hashtag.id %}">{{ hashtag.name }}</a>
           {% endfor %}
     </div>
      </div>
</section>
</div>
<br>
{% endblock %}

crud/blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% block bord %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
    {% for blog in hashtag.blog_set.all %}
      <div class="post-preview">
        <h1>제목 :<a href="{% url 'detail' blog.id %}">{{ blog.title }}</a></h1>
        <p>작성자 : {{ blog.writer }}</p>
        <p>작성 일자 및 시간 : {{ blog.pub_date }}</p>
        {% if posts.image %}
          <img src="{{ posts.image.url }}" width="250" height="250" alt="Card image cap">
        {% endif %}
      </div>
      <hr>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

crud/blog/templates/blog/write.html
{% extends 'blog/base.html' %} 
{% load static %}

{% block bord %}
<section id="about">
    <div class="container px-4 px-lg-5"></div>
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-lg-8 text-center">
              <form method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  <table>
                      {{form.as_table}}
                  </table> 
                  <button type="submit">작성</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}